routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get("/admin", function()
{
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
});
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['guest:admin']], function ()
{
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
});
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth:admin']], function ()
{
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('logout');
});
Route::group(['namespace' => 'Admin', 'middleware' => ['can:' . config('custom_middleware.view_admin'), 'auth:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function ()
{
    Route::group(['namespace' => 'Home', 'prefix' => 'home', 'as' => 'home.', 'middleware' => ['can:' . config('custom_middleware.view_dashboard')]], function ()
    {
        $default    = "index";
        $controller = "HomeController@";
        Route::get('/', $controller . $default)->name('index'); //Default Page
    });
    Route::group(['namespace' => 'Product', 'prefix' => 'product', 'as' => 'product.', 'middleware' => ['can:' . config('custom_middleware.view_product_product')]], function ()
    {
        $default    = "index";
        $controller = "ProductController@";
        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_product_product')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'store'])->name('add'); //Save
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'edit'])->name('edit'); //Update Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'update'])->name('update'); //Update
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_product_product')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
    });

    Route::group(['namespace' => 'OrderStatus', 'prefix' => 'order-status', 'as' => 'order-status.', 'middleware' => ['can:' . config('custom_middleware.view_product_product')]], function ()
    {
        $default    = "index";
        $controller = "OrderStatusController@";
        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_product_product')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'store'])->name('add'); //Save
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'edit'])->name('edit'); //Update Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'update'])->name('update'); //Update
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_product_product')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
    });

    Route::group(['namespace' => 'Customer', 'prefix' => 'customer', 'as' => 'customer.', 'middleware' => ['can:' . config('custom_middleware.view_customer')]], function ()
    {
        $default    = "index";
        $controller = "CustomerController@";

        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_customer')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_customer')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_customer')], 'uses' => $controller . 'store'])->name('add'); //Add Form
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'edit'])->name('edit'); //Add Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'update'])->name('update'); //Add Form
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_customer')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
        Route::get('/change-status/{id}/{active}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'changeStatus'])->name('change-status'); //Change Status
    });
});

app/Http/Controllers/Admin/OrderStatus/OrderStatusController.php
<?php

namespace App\Http\Controllers\Admin\OrderStatus;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Lang;
use Helper;
use DB;
use Illuminate\Support\Str;
use App\AdminModel\OrderStatus\AdminOrderStatus;
use App\Admin;
use App\AdminModel\Product\AdminProduct;

class OrderStatusController extends Controller
{

    private $langFile = 'admin';
    private $module   = '.order_status';

    public function index(Request $request)
    {
        /*
         * Get SortKey and SortOrder from helper
         */
        $sorting    = Helper::getOrderSortingColumn($request);
        $sortKey    = $sorting['sortKey'];
        $sortVal    = $sorting['sortVal'];
        $searchText = $request->q;
        $pageLength = $request->pageLength;

        $orderStatus = new AdminOrderStatus();
        $orderStatus = $orderStatus->getAllData($searchText, $sortKey, $sortVal, $pageLength);
        return view('admin.OrderStatus.index', compact('pageLength', 'searchText', 'sortKey', 'sortVal', 'orderStatus'));
    }

    public function create()
    {
        $customer = new Admin();
        $customer = $customer->all();
        $product  = new AdminProduct();
        $product  = $product->all();
        return view("admin.OrderStatus.add", compact('customer', 'product'));
    }

    public function store(Request $request)
    {
        $request->validate(
                [
                    'order_status' => 'required',
                    'admin_id'     => 'required',
                    'product_id'   => 'required',
                ]
                , [
            'order_status.required' => __($this->langFile . '.error-req-order-status'),
            'admin_id.required'     => __($this->langFile . '.error-req-select'),
            'product_id.required'   => __($this->langFile . '.error-req-select'),
        ]);
        DB::beginTransaction();

        try
        {
            $orderStatus               = new AdminOrderStatus();
            $orderStatus->order_status = $request->order_status;
            $orderStatus->admin_id     = $request->admin_id;
            $orderStatus->product_id   = $request->product_id;
            if ($orderStatus->save())
            {
                DB::commit();
                $status       = 'success';
                $message_text = __($this->langFile . '.add-success');
                $message_text = Str::replaceFirst("#module#", __($this->langFile . $this->module), $message_text);
            }
            else
            {
                DB::rollback();
                $status       = 'error';
                $message_text = __($this->langFile . '.add-error');
                $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
            }
        }
        catch (Throwable $e)
        {
            DB::rollback();
            $status       = 'error';
            $message_text = __($this->langFile . '.add-error');
            $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
        }

        return redirect()->route('admin.order-status.index')->with($status, $message_text);
    }

    public function edit($id)
    {
        $singleRecord = AdminOrderStatus::find($id);
        if ($singleRecord)
        {
            $customer = new Admin();
            $customer = $customer->all();
            $product  = new AdminProduct();
            $product  = $product->all();
            return view("admin.OrderStatus.edit", compact('singleRecord', 'customer', 'product'));
        }
        else
        {
            $status       = 'error';
            $message_text = __($this->langFile . '.record_not_found');
            return redirect()->route('admin.order-status.index')->with($status, $message_text);
        }
    }

    public function update(Request $request, $id)
    {
        $orderStatus = AdminOrderStatus::find($id);
        if ($orderStatus)
        {
            $request->validate(
                    [
                        'order_status' => 'required',
                        'admin_id'     => 'required',
                        'product_id'   => 'required',
                    ]
                    , [
                'order_status.required' => __($this->langFile . '.error-req-order-status'),
                'admin_id.required'     => __($this->langFile . '.error-req-select'),
                'product_id.required'   => __($this->langFile . '.error-req-select'),
            ]);

            DB::beginTransaction();
            try
            {
                $orderStatus->order_status = strtolower($request->order_status);
                $orderStatus->admin_id     = $request->admin_id;
                $orderStatus->product_id   = $request->product_id;

                if ($orderStatus->save())
                {
                    DB::commit();
                    $status       = 'success';
                    $message_text = __($this->langFile . '.update-success');
                    $message_text = Str::replaceFirst("#module#", __($this->langFile . $this->module), $message_text);
                }
                else
                {
                    DB::rollback();
                    $status       = 'error';
                    $message_text = __($this->langFile . '.update-error');
                    $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
                }
            }
            catch (Throwable $e)
            {
                DB::rollback();
                $status       = 'error';
                $message_text = __($this->langFile . '.update-error');
                $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
            }
        }
        else
        {
            $status       = 'error';
            $message_text = __($this->langFile . '.record_not_found');
        }
        return redirect()->route('admin.order-status.index')->with($status, $message_text);
    }

    public function delete($id)
    {
        $orderStatus = AdminOrderStatus::all()->count();
        if ($orderStatus > 1)
        {
            if ($id)
            {
                $record = AdminOrderStatus::find($id);

                if ($record)
                {
                    DB::beginTransaction();
                    try
                    {
                        if ($record->delete())
                        {
                            DB::commit();
                            $status       = 'success';
                            $message_text = __($this->langFile . '.delete-success');
                            $message_text = Str::replaceFirst("#module#", __($this->langFile . $this->module), $message_text);
                        }
                        else
                        {
                            DB::rollback();
                            $status       = 'error';
                            $message_text = __($this->langFile . '.delete-error');
                            $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
                        }
                    }
                    catch (Throwable $e)
                    {
                        DB::rollback();
                        $status       = 'error';
                        $message_text = __($this->langFile . '.delete-error');
                        $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
                    }
                }
                else
                {
                    $status       = 'error';
                    $message_text = __($this->langFile . '.record_not_found');
                }
            }
            else
            {
                $status       = 'error';
                $message_text = __($this->langFile . '.record_not_found');
            }
        }
        else
        {
            $status       = 'error';
            $message_text = __($this->langFile . '.cannot-delete');
        }
        return redirect()->route('admin.order-status.index')->with($status, $message_text);
    }

}

resources/views/admin/OrderStatus/add.blade.php
@extends('layout/main')
@section('page_title',  trans('admin.order'))
@section('additional_css')
@endsection
@section('content')
@include('layout/toaster')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('admin.order_status')}}</h1>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{route('admin.home.index')}}">{{__('admin.home')}}</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.order-status.index')}}">{{__('admin.order_status')}}</a></li>
                        <li class="breadcrumb-item active">{{__('admin.add')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="card {{config('custom.card-primary')}}">
                <div class="card-header">
                    <h3 class="card-title">{{__('admin.add')}}</h3>
                </div>
                <form method="post" action="{{route('admin.order-status.add')}}">
                    @csrf
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xs-12 col-md-4">
                                <div class="form-group">
                                    <label>{{__('admin.select-customer')}}</label><span class="required"></span>
                                    <select name="admin_id"  class="form-control select2 select-customer {{config('custom.select2-css')}}" data-dropdown-css-class="{{config('custom.select2-css')}}">
                                        @foreach($customer as $cust)
                                        <option value="{{$cust->id}}" {{ (collect(old('admin_id'))->contains($cust->id)) ? 'selected':'' }}>
                                            {{$cust?$cust->first_name.' '.$cust->last_name:''}}</option>
                                        @endforeach
                                    </select>
                                    @error('admin_id')
                                    <div class="text-red">{{ $message }}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-4">
                                <div class="form-group">
                                    <label>{{__('admin.select-product')}}</label><span class="required"></span>
                                    <select name="product_id"  class="form-control select2 select-product {{config('custom.select2-css')}}" data-dropdown-css-class="{{config('custom.select2-css')}}">
                                        @foreach($product as $record)
                                        <option value="{{$record->id}}" {{ (collect(old('product_id'))->contains($record->id)) ? 'selected':'' }}>
                                            {{$record?$record->product_name:''}}</option>
                                        @endforeach
                                    </select>
                                    @error('product_id')
                                    <div class="text-red">{{ $message }}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-4">
                                <div class="form-group">
                                    <label>{{__('admin.order_status')}}</label><span class="required"></span>
                                    <input type="text" class="form-control length-10" placeholder="{{__('admin.order_status')}}" name="order_status" type="text" value="{{old('order_status')}}">
                                    @error('order_status')
                                    <div class="text-red">{{ $message }}</div>
                                    @endif
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <span class="float-left">{!!__('admin.additional_notes')!!}</span>
                        <div class="btn-toolbar float-right">
                            <div class="btn-group mr-2">
                                <a href="{{route('admin.order-status.index')}}" class="{{config('custom.btn-danger-form')}}" title="{{__('admin.cancel')}}">{{__('admin.cancel')}}</a>
                            </div>
                            <div class="btn-group">
                                <button type="submit" class="{{config('custom.btn-success-form')}}" title="{{__('admin.submit')}}">{{__('admin.submit')}}</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
@endsection
@section('page_specific_js')
<script>
    $(document).ready(function ()
    {
        $(".select-product").select2({
            placeholder: "{{__('admin.select-product')}}",
            allowClear: true
        });
        $(".select-customer").select2({
            placeholder: "{{__('admin.select-customer')}}",
            allowClear: true
        });
    });
</script>
@endsection

resources/views/admin/OrderStatus/index.blade.php
@extends('layout/main')
@section('page_title',  trans('admin.product'))
@section('additional_css')
<link rel="stylesheet" href="{{asset('plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@endsection
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            @include('layout/toaster')
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('admin.product')}}</h1>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{route('admin.home.index')}}">{{__('admin.home')}}</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.product.index')}}">{{__('admin.product')}}</a></li>
                        <li class="breadcrumb-item active">{{__('admin.list')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-12">
                    <form class="list-table" method="get" action="{{route('admin.order-status.index')}}">
                        @if(false)
                        <div class="row">
                            <div class="col-12">
                                <section class="content">
                                    <div class="card {{config('custom.card-primary')}}">                                      

                                        <div class="card-footer">
                                            <div class="btn-toolbar float-right">
                                                <div class="btn-group">
                                                    <button type="submit" class="{{config('custom.btn-success-form')}}" title="{{__('admin.search')}}">{{__('admin.search')}}</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>
                            </div>
                        </div>                       
                        @endif
                        <div class="card {{config('custom.card-primary')}}">
                            <div class="table-card card-header pl-0">
                                <div class="card-tools w-100">
                                    <div class="input-group input-group-sm float-right custom-search">
                                        <input type="text" name="q" class="form-control float-right float-sm-right" placeholder="{{__('admin.search')}}" value="{{isset($searchText)?$searchText:''}}">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-default" title="{{__('admin.search')}}"><i class="fas fa-search"></i></button>
                                        </div>
                                        <a class="pl-2"  href="{{route('admin.order-status.add')}}"><button type="button" class="{{config('custom.btn-primary','btn btn-outline-primary')}} add-new-btn" title="{{__('admin.add')}}">{{__('admin.add')}}</button></a>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <table data-model="AdminOrderStatus" class="table normal-table table-striped">
                                <thead>
                                    <tr>
                                        <th class="asc-desc text-center" id="@if($sortKey=='id'){{$sortVal}}@endif">{{__('admin.first_column')}}<input @if($sortKey!='id')disabled=""@endif  type="hidden" name="id" value="@if($sortKey=='id'){{$sortVal}}@endif"></th>
                                        <th class="asc-desc" id="@if($sortKey=='product_id'){{$sortVal}}@endif">{{__('admin.product_name')}}<input @if($sortKey!='product_id')disabled=""@endif  type="hidden" name="product_id" value="@if($sortKey=='product_id'){{$sortVal}}@endif"></th>
                                        <th class=" asc-desc" id="@if($sortKey=='admin_id'){{$sortVal}}@endif">{{__('admin.customer_name')}}<input @if($sortKey!='admin_id')disabled=""@endif  type="hidden" name="admin_id" value="@if($sortKey=='admin_id'){{$sortVal}}@endif"></th>
                                        <th class=" asc-desc" id="@if($sortKey=='order_status'){{$sortVal}}@endif">{{__('admin.order_status')}}<input @if($sortKey!='order_status')disabled=""@endif  type="hidden" name="order_status" value="@if($sortKey=='order_status'){{$sortVal}}@endif"></th>
                                        <th class="text-center">{{__('admin.action')}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($orderStatus as $record)
                                    <tr id="{{$record->id}}">
                                        <td class="text-center">{{ucfirst($record->id)}}</td>
                                        <?php
                                        $product  = $record->getProduct($record->product_id);
                                        $customer = $record->getCustomer($record->admin_id);
                                        ?>
                                        <td>{{$product?ucfirst($product->product_name):''}}</td>
                                        <td>{{ucfirst($customer->first_name.' '.$customer->last_name)}}</td>
                                        <td>{{$record?ucfirst($record->order_status):''}}</td>
                                        <td class="text-center">
                                            <a href="{{route('admin.order-status.edit',['id'=>$record->id])}}"><button type="button" class="{{config('custom.btn-primary','btn btn-outline-primary btn-sm')}}" title="{{__('admin.edit')}}"><i class="fas fa-edit"></i></button></a>
                                            <a onclick="showSweetAlert('{{route('admin.order-status.delete',['id'=>$record->id])}}')"><button type="button" class="{{config('custom.btn-danger','btn btn-outline-danger btn-sm')}}" title="{{__('admin.delete')}}"><i class="fas fa-trash"></i></button></a>
                                        </td>
                                    </tr>
                                    @empty
                                    @endforelse
                                </tbody>
                            </table>
                            <!-- /.card-body -->
                        </div>
                        <div class="table-pagination pt20 float-right">
                            {{$orderStatus->appends(request()->input())->links()}}
                        </div>
                    </form>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection
@section('page_specific_js')
@include('common/sorting')
@include('layout/select2') 
@endsection