routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get("/admin", function()
{
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
});
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['guest:admin']], function ()
{
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
});
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth:admin']], function ()
{
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('logout');
});
Route::group(['namespace' => 'Admin', 'middleware' => ['can:' . config('custom_middleware.view_admin'), 'auth:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function ()
{
    Route::group(['namespace' => 'Home', 'prefix' => 'home', 'as' => 'home.', 'middleware' => ['can:' . config('custom_middleware.view_dashboard')]], function ()
    {
        $default    = "index";
        $controller = "HomeController@";
        Route::get('/', $controller . $default)->name('index'); //Default Page
    });
    Route::group(['namespace' => 'Product', 'prefix' => 'product', 'as' => 'product.', 'middleware' => ['can:' . config('custom_middleware.view_product_product')]], function ()
    {
        $default    = "index";
        $controller = "ProductController@";
        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_product_product')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'store'])->name('add'); //Save
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'edit'])->name('edit'); //Update Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'update'])->name('update'); //Update
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_product_product')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
    });

    Route::group(['namespace' => 'OrderStatus', 'prefix' => 'order-status', 'as' => 'order-status.', 'middleware' => ['can:' . config('custom_middleware.view_product_product')]], function ()
    {
        $default    = "index";
        $controller = "OrderStatusController@";
        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_product_product')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'store'])->name('add'); //Save
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'edit'])->name('edit'); //Update Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'update'])->name('update'); //Update
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_product_product')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
    });

    Route::group(['namespace' => 'Customer', 'prefix' => 'customer', 'as' => 'customer.', 'middleware' => ['can:' . config('custom_middleware.view_customer')]], function ()
    {
        $default    = "index";
        $controller = "CustomerController@";

        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_customer')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_customer')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_customer')], 'uses' => $controller . 'store'])->name('add'); //Add Form
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'edit'])->name('edit'); //Add Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'update'])->name('update'); //Add Form
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_customer')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
        Route::get('/change-status/{id}/{active}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'changeStatus'])->name('change-status'); //Change Status
    });
});

resources/views/layout/common_scripts.blade.php
<script src="{{asset('plugins/jquery/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
$.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{asset('plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('dist/js/adminlte.min.js')}}"></script>

resources/views/layout/datatable.blade.php
<link rel="stylesheet" href="{{asset('plugins/datatables-rowreorder/css/rowReorder.bootstrap4.min.css')}}">
<script src="{{asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/datatables-rowreorder/js/dataTables.rowReorder.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script>
$(document).ready(function ()
{
    var oTable = $('.normal-table').DataTable({
        "paging": false,
        "lengthChange": false,
        "searching": false,
        "ordering": false,
        "info": false,
        "autoWidth": false,
        "responsive": true,
        "oLanguage": {
            "sEmptyTable": "{{__('admin.no_record_found')}}"
        }
    });
});
</script>

resources/views/layout/footer.blade.php
<style>
    p{
        margin-bottom: 0px;
    }
</style>

resources/views/layout/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{asset('plugins/fontawesome-free/css/all.min.css')}}">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    @yield('additional_css')
    <link rel="stylesheet" href="{{asset('dist/css/adminlte.min.css')}}">
    <link rel="stylesheet" href="{{asset('custom/css/custom.css')}}">

    <style>
        .help-block{
            font-weight: normal;
            font-size: 11px;
            margin-bottom: 0;
        }
        .hr-custom{
            margin-top:0px; 
        }
        .page-item.active .page-link{
            background-color:#343a40;
            border-color:#343a40;
        }
        .page-link{
            color:#343a40;
        }
        .page-link:hover{
            color:#343a40;
        }
        a{
            color:#343a40;
        }
        .table-card{
            border-bottom: none;
        }
        table.dataTable{
            margin-bottom: 0px !important;
            /*            padding: 3px;*/
        }
        .pb-0{
            padding-bottom: 0px;
        }
        table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > td.dtr-control::before, table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > th.dtr-control::before {
            left: 7px
        }
        .custom-search{
            width: 15%;
        }
        .pl-0
        {
            padding-left: 0px
        }
        .pl-2{
            padding-left: 2px;
        }
        .w-100{
            width: 100%;
        }
        .card-header{
            padding-bottom: 7px;
        }
        @media only screen and (min-width: 250px) and (max-width: 1800px) {
            .card-header > .card-tools .input-group, .card-header > .card-tools .nav, .card-header > .card-tools .pagination {
                margin-bottom: 2px;
            }
            .custom-search{
                width: 70%;
            }
            .table-card{
                padding-bottom: 0px;
            }
        }

    </style>
</head>

resources/views/layout/main.blade.php
<!DOCTYPE html>
<html>

    <!--Head-->
    @include('layout/head')
    <!--/ Head-->
    <body class="hold-transition sidebar-mini layout-fixed">
        <div class="wrapper">
            <!-- Navbar -->
            @include('layout/navbar')
            <!-- /.navbar -->
            <!-- Main Sidebar Container -->
            @include('layout/sidebar')
            <!-- Content Wrapper. Contains page content -->
            <div id="pageloader">
                <i class="fa fa-spinner fa-spin fa-5x fa-fw text-primary"></i><span class="sr-only">Loading...</span>
            </div>
            @yield('content')
            <!-- /.content-wrapper -->
            <!--Footer-->
            @include('layout/footer')
            <!--/ Footer-->
            <!-- Control Sidebar -->
            <!-- /.control-sidebar -->
        </div>
        <!-- ./wrapper -->
        <!-- jQuery -->
        <!--Common Scripts-->
        @include('layout/common_scripts')
        @yield('page_specific_js')
        <script>
            $(document).ready(function ()
            {
                setTimeout(function ()
                {
                    $('.alert').fadeOut('slow');
                }, 5000); // <-- time in milliseconds

                $("form").on("submit", function (e)
                {
                    $("#pageloader").fadeIn();
                });//submit
                $(".a-submit").on("click", function (e)
                {
                    $("#pageloader").fadeIn();
                });//submit
                /*
                 * Input must be a number only - Common Validation
                 */
                $(".number-input").keypress(function (e)
                {
                    if ((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57))
                    {
                        event.preventDefault();
                    }
                });

                /*
                 * Input must be anumber or float only  - Custom validation
                 */
                $('.float-input').bind('paste', function ()
                {
                    var self = this;
                    setTimeout(function ()
                    {
                        if (!/^\d*(\.\d{1,2})+$/.test($(self).val()))
                            $(self).val('');
                    }, 0);
                });

                $('.float-input').keypress(function (e)
                {
                    var character = String.fromCharCode(e.keyCode)
                    var newValue = this.value + character;
                    if (isNaN(newValue) || hasDecimalPlace(newValue, 3))
                    {
                        e.preventDefault();
                        return false;
                    }
                });

                function hasDecimalPlace(value, x)
                {
                    var pointIndex = value.indexOf('.');
                    return  pointIndex >= 0 && pointIndex < value.length - x;
                }

                /*
                 * Input must be sting only - Custom validation
                 */
                $('.string-input').bind('keyup blur', function ()
                {
                    $(this).val($(this).val().replace(/[^a-z]/g, ''));
                });

                /*
                 * Input must be sting with special character - Custom validation
                 */
                $('.special-char-input').bind('keyup blur', function ()
                {
                    $(this).val($(this).val().replace(/[^A-Za-z_@./#&+-]*$/, ''));
                });

                /*
                 * Input max length
                 */
                $("input[type=text]").attr('maxlength', 100);
                $("input[type=password]").attr('maxlength', 20);
                $("input[type=number]").attr('maxlength', 15);
                $(".length-2").attr('maxlength', 2);
                $(".length-3").attr('maxlength', 3);
                $(".length-4").attr('maxlength', 4);
                $(".length-5").attr('maxlength', 5);
                $(".length-6").attr('maxlength', 6);
                $(".length-8").attr('maxlength', 8);
                $(".length-9").attr('maxlength', 9);
                $(".length-10").attr('maxlength', 10);
                $(".length-20").attr('maxlength', 20);
                $(".length-28").attr('maxlength', 28);
                $(".length-11").attr('maxlength', 11);
                $(".length-15").attr('maxlength', 15);
                $(".length-25").attr('maxlength', 25);
                $(".length-30").attr('maxlength', 30);
                $(".length-40").attr('maxlength', 40);
                $(".length-70").attr('maxlength', 70);
                $(".length-75").attr('maxlength', 75);
                $(".length-50").attr('maxlength', 50);
                $(".length-100").attr('maxlength', 100);
                $(".length-150").attr('maxlength', 150);
                $(".length-500").attr('maxlength', 500);
                $(".length-1000").attr('maxlength', 1000);
                $(".required").next().attr('required', 'required');
             
            });
        </script>
        <!--/ Common Scripts-->
    </body>
</html>

resources/views/layout/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown user-menu">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
               Logout
            </a>
            <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <li class="user-footer">
                    <a class="logout-link btn btn-default btn-flat float-right" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">{{__('admin.logout')}}</a>
                </li>
            </ul>
        </li>
    </ul>
    <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
        @csrf
    </form>
</nav>

resources/views/layout/select2.blade.php
<script src="{{asset('plugins/select2/js/select2.full.min.js')}}"></script>
<script>
$(document).ready(function ()
{
    $('.select2').select2();
});
</script>

resources/views/layout/sidebar.blade.php
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">{{strtoupper(Auth::user()->name)}}</li>
                <li class="nav-item">
                    <a href="{{route('admin.customer.index')}}" class="nav-link {{ request()->routeIs('admin.customer.*') ?'active':'' }}">
                        <i class="nav-icon fas fa-user"></i>
                        <p>{{__('admin.menu_customer')}}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.product.index')}}" class="nav-link {{ request()->routeIs('admin.product.*') ?'active':'' }}">
                        <i class="nav-icon fas fa-user"></i>
                        <p>{{__('admin.menu_product')}}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.order-status.index')}}" class="nav-link {{ request()->routeIs('admin.order-status.*') ?'active':'' }}">
                        <i class="nav-icon fas fa-user"></i>
                        <p>{{__('admin.menu_order_status')}}</p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>

resources/views/layout/sweetalert.blade.php
<link rel="stylesheet" href="{{asset('plugins/sweetalert2/sweetalert2.min.css')}}">
<script src="{{asset('plugins/sweetalert2/sweetalert2.min.js')}}"></script>
<script>

function permission_denied()
{
    Swal.fire("Alert", "Permission Denied", "error");
}

function showSweetAlert(url)
{
    Swal.fire({
        title: '{{__("admin.are_you_sure")}}',
        text: '{{__("admin.not_able_to_recover")}}',
        type: 'danger',
        showCancelButton: true,
        confirmButtonText: '{{__("admin.yes_delete")}}',
        cancelButtonText: '{{__("admin.no_keep_it")}}'
    }).then((result) => {
        if (result.value)
        {
            window.location.href = url;
        }
    });
}
function showSweetAlertImage(url, id = '')
{
    Swal.fire({
        title: '{{__("admin.are_you_sure")}}',
        text: '{{__("admin.not_able_to_recover_file")}}',
        type: 'danger',
        showCancelButton: true,
        confirmButtonText: '{{__("admin.yes_delete")}}',
        cancelButtonText: '{{__("admin.no_keep_it")}}'
    }).then((result) => {
        if (result.value)
        {
            $("#pageloader").fadeIn();
            $.ajax({
                type: 'GET',
                url: url,
                success: (data) => {
                    $("#" + id).remove();
                    if (data.status)
                    {
                        addMoreCount--;
                        changeCount();
                        show_success(data.message);
                    }
                    else
                    {
                        show_error('{{__("admin.swal_error")}}', data.message);
                    }
                },
                error: function (xhr)
                {
                    show_error('{{__("admin.swal_error")}}', '{{__("admin.swal_error_message")}}');
                },
                complete: function (data)
                {
                    $("#pageloader").fadeOut();
                }
            });
        }
    });
}
function show_error(error, message)
{
    Swal.fire(error, message, "error");
}

function show_success(message)
{
    Swal.fire('{{__("admin.swal_success")}}', message, 'success');
}
</script>

resources/views/layout/toaster.blade.php
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <!--<h4><i class="icon fa fa-check"></i> Alert!</h4>-->
    <i class="icon fa fa-check"></i> {{ session()->get('success') }}
</div>
@endif

@if(session()->has('error'))
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <!--<h4><i class="icon fa fa-ban"></i> Alert!</h4>-->
    <i class="icon fa fa-ban"></i>{{ session()->get('error') }}
</div>
@endif
@if(isset($status) && !empty($status) && $status=='success')
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <!--<h4><i class="icon fa fa-check"></i> Alert!</h4>-->
    <i class="icon fa fa-check"></i>{{ $message_text }}
</div>
@endif

@if(isset($status) && !empty($status) && $status=='error')
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <!--<h4><i class="icon fa fa-ban"></i> Alert!</h4>-->
    <i class="icon fa fa-ban"></i>{{ $message_text }}
</div>
@endif