routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get("/admin", function()
{
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
});
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['guest:admin']], function ()
{
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
});
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth:admin']], function ()
{
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('logout');
});
Route::group(['namespace' => 'Admin', 'middleware' => ['can:' . config('custom_middleware.view_admin'), 'auth:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function ()
{
    Route::group(['namespace' => 'Home', 'prefix' => 'home', 'as' => 'home.', 'middleware' => ['can:' . config('custom_middleware.view_dashboard')]], function ()
    {
        $default    = "index";
        $controller = "HomeController@";
        Route::get('/', $controller . $default)->name('index'); //Default Page
    });
    Route::group(['namespace' => 'Product', 'prefix' => 'product', 'as' => 'product.', 'middleware' => ['can:' . config('custom_middleware.view_product_product')]], function ()
    {
        $default    = "index";
        $controller = "ProductController@";
        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_product_product')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'store'])->name('add'); //Save
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'edit'])->name('edit'); //Update Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'update'])->name('update'); //Update
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_product_product')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
    });

    Route::group(['namespace' => 'OrderStatus', 'prefix' => 'order-status', 'as' => 'order-status.', 'middleware' => ['can:' . config('custom_middleware.view_product_product')]], function ()
    {
        $default    = "index";
        $controller = "OrderStatusController@";
        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_product_product')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'store'])->name('add'); //Save
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'edit'])->name('edit'); //Update Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'update'])->name('update'); //Update
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_product_product')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
    });

    Route::group(['namespace' => 'Customer', 'prefix' => 'customer', 'as' => 'customer.', 'middleware' => ['can:' . config('custom_middleware.view_customer')]], function ()
    {
        $default    = "index";
        $controller = "CustomerController@";

        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_customer')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_customer')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_customer')], 'uses' => $controller . 'store'])->name('add'); //Add Form
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'edit'])->name('edit'); //Add Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'update'])->name('update'); //Add Form
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_customer')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
        Route::get('/change-status/{id}/{active}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'changeStatus'])->name('change-status'); //Change Status
    });
});

app/Http/Controllers/Admin/Product/ProductController.php
<?php

namespace App\Http\Controllers\Admin\Product;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Lang;
use Helper;
use DB;
use App\AdminModel\Product\AdminProduct;

class ProductController extends Controller
{

    private $langFile = 'admin';
    private $module   = '.product';
    private $mediaId  = 1;

    public function index(Request $request)
    {
        /*
         * Get SortKey and SortOrder from helper
         */
        $sorting    = Helper::getOrderSortingColumn($request);
        $sortKey    = $sorting['sortKey'];
        $sortVal    = $sorting['sortVal'];
        $searchText = $request->q;
        $pageLength = $request->pageLength;
        $product    = new AdminProduct();
        $product    = $product->getAllData($searchText, $sortKey, $sortVal, $pageLength);
        return view('admin.product.index', compact('sortKey', 'sortVal', 'searchText', 'product', 'pageLength'));
    }

    public function create()
    {
        return view("admin.product.add");
    }

    public function store(Request $request)
    {
        /*
         * Validations
         */
        $validationRule    = [
            'product_code'     => 'required',
            'product_name'     => 'required',
            'product_price'    => 'required|numeric',
            'product_quantity' => 'required|numeric',
        ];
        $validationMessage = [
            'product_name.required'     => __($this->langFile . '.error-product-req-product-code'),
            'product_code.required'     => __($this->langFile . '.error-product-req-product-code'),
            'product_price.required'    => __($this->langFile . '.error-product-req-reg-price'),
            'product_price.numeric'     => __($this->langFile . '.error-product-numeric-reg-price'),
            'product_quantity.required' => __($this->langFile . '.error-product-req-product_quantity'),
            'product_quantity.numeric'  => __($this->langFile . '.error-product-numeric-product_quantity'),
        ];

        $validatedData = $request->validate($validationRule, $validationMessage);

        /*
         * All validation Passed
         */

        DB::beginTransaction();

        try
        {
            /*
             * Insert status Flag
             */
            $flag = true;

            $model = new AdminProduct();

            $model->product_name        = $request->product_name;
            $model->product_code        = $request->product_code;
            $model->product_quantity    = $request->product_quantity;
            $model->product_description = $request->product_description;
            $model->product_price       = $request->product_price;

            /*
             * Save Main Record
             */
            if ($model->save())
            {
                if ($flag)
                {
                    DB::commit();
                    $status       = 'success';
                    $message_text = __($this->langFile . '.add-success');
                    $message_text = str_replace("#module#", __($this->langFile . $this->module), $message_text);
                }
                else
                {
                    DB::rollback();
                    $status       = 'error';
                    $message_text = __($this->langFile . '.add-error');
                    $message_text = str_replace("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
                }
            }
        }
        catch (Throwable $e)
        {
            DB::rollback();
            $status       = 'error';
            $message_text = __($this->langFile . '.add-error');
            $message_text = str_replace("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
        }

        return redirect()->route('admin.product.index')->with($status, $message_text);
    }

    public function edit($id)
    {
        $singleRecord = AdminProduct::find($id);

        if ($singleRecord)
        {

            return view("admin.product.edit", compact('singleRecord'));
        }
        else
        {
            return redirect()->route('admin.product.index')->with('error', __($this->langFile . '.record_not_found'));
        }
    }

    public function update(Request $request, $id)
    {
        $model = AdminProduct::find($id);
        if ($model)
        {
            /*
             * Validations
             */
            $validationRule    = [
                'product_code'     => 'required',
                'product_name'     => 'required',
                'product_price'    => 'required|numeric',
                'product_quantity' => 'required|numeric',
            ];
            $validationMessage = [
                'product_name.required'     => __($this->langFile . '.error-product-req-product-code'),
                'product_code.required'     => __($this->langFile . '.error-product-req-product-code'),
                'product_price.required'    => __($this->langFile . '.error-product-req-reg-price'),
                'product_price.numeric'     => __($this->langFile . '.error-product-numeric-reg-price'),
                'product_quantity.required' => __($this->langFile . '.error-product-req-product_quantity'),
                'product_quantity.numeric'  => __($this->langFile . '.error-product-numeric-product_quantity'),
            ];


            $validatedData = $request->validate($validationRule, $validationMessage);

            /*
             * All validation Passed
             */
            DB::beginTransaction();
            try
            {
                /*
                 * Insert status Flag
                 */
                $flag = true;

                $model->product_name        = $request->product_name;
                $model->product_code        = $request->product_code;
                $model->product_quantity    = $request->product_quantity;
                $model->product_description = $request->product_description;
                $model->product_price       = $request->product_price;

                /*
                 * Save Main Record
                 */
                if ($model->save())
                {
                    if ($flag)
                    {
                        DB::commit();
                        $status       = 'success';
                        $message_text = __($this->langFile . '.update-success');
                        $message_text = str_replace("#module#", __($this->langFile . $this->module), $message_text);
                    }
                    else
                    {
                        DB::rollback();
                        $status       = 'error';
                        $message_text = __($this->langFile . '.update-error');
                        $message_text = str_replace("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
                    }
                }
            }
            catch (Throwable $e)
            {
                DB::rollback();
                $status       = 'error';
                $message_text = __($this->langFile . '.update-error');
                $message_text = str_replace("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
            }
        }
        else
        {
            $status       = 'error';
            $message_text = __($this->langFile . '.record_not_found');
        }

        return redirect()->route('admin.product.index')->with($status, $message_text);
    }

    /*
     * Delete
     */

    public function delete($id)
    {
        if ($id)
        {
            $record = AdminProduct::find($id);

            if ($record)
            {
                DB::beginTransaction();

                try
                {

                    if ($record->delete())
                    {
                        DB::commit();
                        $status       = 'success';
                        $message_text = __($this->langFile . '.delete-success');
                        $message_text = str_replace("#module#", __($this->langFile . $this->module), $message_text);
                    }
                    else
                    {
                        DB::rollback();
                        $status       = 'error';
                        $message_text = __($this->langFile . '.delete-error');
                        $message_text = str_replace("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
                    }
                }
                catch (Throwable $e)
                {
                    DB::rollback();
                    $status       = 'error';
                    $message_text = __($this->langFile . '.delete-error');
                    $message_text = str_replace("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
                }
            }
            else
            {
                $status       = 'error';
                $message_text = __($this->langFile . '.record_not_found');
            }
        }
        else
        {
            $status       = 'error';
            $message_text = __($this->langFile . '.record_not_found');
        }
        return redirect()->route('admin.product.index')->with($status, $message_text);
    }

}

resources/views/admin/Product/edit.blade.php
@extends('layout/main')
@section('page_title',  trans('admin.product'))
@section('additional_css')
@endsection
@section('content')
@include('layout/toaster')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('admin.product')}}</h1>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{route('admin.home.index')}}">{{__('admin.home')}}</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.product.index')}}">{{__('admin.product')}}</a></li>
                        <li class="breadcrumb-item active">{{__('admin.edit')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="card {{config('custom.card-primary')}}">
                <div class="card-header">
                    <h3 class="card-title">{{__('admin.edit')}}</h3>
                </div>
                <form method="post" action="{{route('admin.product.update',['id' => $singleRecord->id])}}">
                    @csrf
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-xs-12">
                                <div class="form-group">
                                    <label>{{__('admin.product_name')}}</label><span class="required"></span>
                                    <input name="product_name" type="text" class="form-control {{ $errors->has('product_name') ? 'is-invalid':'' }}" placeholder="{{__('admin.product_name')}}" value="{{old('product_name',$singleRecord->product_name)}}">
                                    @error('product_name')
                                    <div class="text-red">{{ $message }}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6">
                                <div class="form-group">
                                    <label>{{__('admin.product_code')}}</label><span class="required"></span>
                                    <input class="form-control length-10" placeholder="{{__('admin.product_code')}}" name="product_code" type="text" value="{{old('product_code',$singleRecord->product_code)}}">
                                    @error('product_code')
                                    <div class="text-red">{{ $message }}</div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-md-6">
                                <div class="form-group">
                                    <label>{{__('admin.product_price')}}</label><span class="required"></span>
                                    <input class="form-control float-input length-10" placeholder="{{__('admin.product_price')}}" name="product_price" type="text" value="{{old('product_price',$singleRecord->product_price)}}">
                                    @error('product_price')
                                    <div class="text-red">{{ $message }}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6">
                                <div class="form-group">
                                    <label>{{__('admin.product_quantity')}}</label><span class="required"></span>
                                    <input  class="form-control float-input length-10" placeholder="{{__('admin.product_quantity')}}" name="product_quantity" type="text" value="{{old('product_quantity',$singleRecord->product_quantity)}}">
                                    @error('product_quantity')
                                    <div class="text-red">{{ $message }}</div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 col-xs-12">
                                <div class="form-group">
                                    <label>{{__('admin.product_description')}}</label>
                                    <textarea  class="textarea form-control {{ $errors->has('product_description') ? 'is-invalid':'' }}" placeholder="{{__('admin.product_description')}} " id="product_description" name="product_description" rows="4" cols="300">{{old('product_description',$singleRecord->product_description)}}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <span class="float-left">{!!__('admin.additional_notes')!!}</span>
                        <div class="btn-toolbar float-right">
                            <div class="btn-group mr-2">
                                <a href="{{route('admin.product.index')}}" class="{{config('custom.btn-danger-form')}}" title="{{__('admin.cancel')}}">{{__('admin.cancel')}}</a>
                            </div>
                            <div class="btn-group">
                                <button type="submit" class="{{config('custom.btn-success-form')}}" title="{{__('admin.update')}}">{{__('admin.update')}}</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
@endsection
@section('page_specific_js')
@endsection

resources/views/admin/Product/index.blade.php
@extends('layout/main')
@section('page_title',  trans('admin.product'))
@section('additional_css')
<link rel="stylesheet" href="{{asset('plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@endsection
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            @include('layout/toaster')
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('admin.product')}}</h1>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{route('admin.home.index')}}">{{__('admin.home')}}</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.product.index')}}">{{__('admin.product')}}</a></li>
                        <li class="breadcrumb-item active">{{__('admin.list')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-12">
                    <form class="list-table" method="get" action="{{route('admin.product.index')}}">
                  
                        <div class="card {{config('custom.card-primary')}}">
                            <div class="table-card card-header pl-0">
                                <div class="card-tools w-100">
                                    <div class="input-group input-group-sm float-right custom-search">
                                        <input type="text" name="q" class="form-control float-right float-sm-right" placeholder="{{__('admin.search')}}" value="{{isset($searchText)?$searchText:''}}">

                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-default" title="{{__('admin.search')}}"><i class="fas fa-search"></i></button>
                                        </div>
                                        <a class="pl-2"  href="{{route('admin.product.add')}}"><button type="button" class="{{config('custom.btn-primary','btn btn-outline-primary')}} add-new-btn" title="{{__('admin.add')}}">{{__('admin.add')}}</button></a>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <table data-model="AdminProduct" class="table normal-table table-striped">
                                <thead>
                                    <tr>
                                        <th class="asc-desc text-center" id="@if($sortKey=='id'){{$sortVal}}@endif">{{__('admin.first_column')}}<input @if($sortKey!='id')disabled=""@endif  type="hidden" name="id" value="@if($sortKey=='id'){{$sortVal}}@endif"></th>
                                        <th class="asc-desc" id="@if($sortKey=='product_name'){{$sortVal}}@endif">{{__('admin.product_name')}}<input @if($sortKey!='product_name')disabled=""@endif  type="hidden" name="product_name" value="@if($sortKey=='product_name'){{$sortVal}}@endif"></th>
                                        <th class="text-center asc-desc" id="@if($sortKey=='product_price'){{$sortVal}}@endif">{{__('admin.product_price')}}<input @if($sortKey!='product_price')disabled=""@endif  type="hidden" name="product_price" value="@if($sortKey=='product_price'){{$sortVal}}@endif"></th>
                                        <th class="text-center asc-desc" id="@if($sortKey=='product_quantity'){{$sortVal}}@endif">{{__('admin.product_quantity_index')}}<input @if($sortKey!='product_quantity')disabled=""@endif  type="hidden" name="product_quantity" value="@if($sortKey=='product_quantity'){{$sortVal}}@endif"></th>
                                        <th class="text-center">{{__('admin.action')}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($product as $record)
                                    <tr id="{{$record->id}}">
                                        <td class="text-center">{{ucfirst($record->id)}}</td>
                                        <td>{{ucfirst($record->product_name)}}</td>
                                        <td class="text-center">{{$record->product_price}}</td>
                                        <td class="text-center">
                                            @if($record->product_quantity)
                                            {{$record->product_quantity}}
                                            @else
                                            <span class='badge badge-danger'>{{__('admin.out_of_stock')}}</span>
                                            @endif
                                        </td>

                                        <td class="text-center">
                                            <a href="{{route('admin.product.edit',['id'=>$record->id])}}"><button type="button" class="{{config('custom.btn-primary','btn btn-outline-primary btn-sm')}}" title="{{__('admin.edit')}}"><i class="fas fa-edit"></i></button></a>
                                            <a onclick="showSweetAlert('{{route('admin.product.delete',['id'=>$record->id])}}')"><button type="button" class="{{config('custom.btn-danger','btn btn-outline-danger btn-sm')}}" title="{{__('admin.delete')}}"><i class="fas fa-trash"></i></button></a>
                                        </td>
                                    </tr>
                                    @empty
                                    @endforelse
                                </tbody>
                            </table>
                            <!-- /.card-body -->
                        </div>
                        <div class="table-pagination pt20 float-right">
                            {{$product->appends(request()->input())->links()}}
                        </div>
                    </form>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection
@section('page_specific_js')
@include('common/sorting')
@include('layout/sweetalert')
@include('layout/datatable')
@include('layout/select2') 
<script>
    $(document).ready(function ()
    {
    $(".select-category").select2({
    placeholder: "{{__('admin.filter_by_category')}}",
            allowClear: true
    });
    });
</script>
@endsection