routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get("/admin", function()
{
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
});
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['guest:admin']], function ()
{
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login');
});
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth:admin']], function ()
{
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('logout');
});
Route::group(['namespace' => 'Admin', 'middleware' => ['can:' . config('custom_middleware.view_admin'), 'auth:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function ()
{
    Route::group(['namespace' => 'Home', 'prefix' => 'home', 'as' => 'home.', 'middleware' => ['can:' . config('custom_middleware.view_dashboard')]], function ()
    {
        $default    = "index";
        $controller = "HomeController@";
        Route::get('/', $controller . $default)->name('index'); //Default Page
    });
    Route::group(['namespace' => 'Product', 'prefix' => 'product', 'as' => 'product.', 'middleware' => ['can:' . config('custom_middleware.view_product_product')]], function ()
    {
        $default    = "index";
        $controller = "ProductController@";
        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_product_product')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'store'])->name('add'); //Save
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'edit'])->name('edit'); //Update Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'update'])->name('update'); //Update
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_product_product')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
    });

    Route::group(['namespace' => 'OrderStatus', 'prefix' => 'order-status', 'as' => 'order-status.', 'middleware' => ['can:' . config('custom_middleware.view_product_product')]], function ()
    {
        $default    = "index";
        $controller = "OrderStatusController@";
        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_product_product')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_product_product')], 'uses' => $controller . 'store'])->name('add'); //Save
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'edit'])->name('edit'); //Update Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_product_product')], 'uses' => $controller . 'update'])->name('update'); //Update
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_product_product')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
    });

    Route::group(['namespace' => 'Customer', 'prefix' => 'customer', 'as' => 'customer.', 'middleware' => ['can:' . config('custom_middleware.view_customer')]], function ()
    {
        $default    = "index";
        $controller = "CustomerController@";

        Route::get('/', ['middleware' => ['can:' . config('custom_middleware.view_customer')], 'uses' => $controller . $default])->name('index'); //Default Page
        Route::get('/add', ['middleware' => ['can:' . config('custom_middleware.create_customer')], 'uses' => $controller . 'create'])->name('add'); //Add Form
        Route::post('/add', ['middleware' => ['can:' . config('custom_middleware.create_customer')], 'uses' => $controller . 'store'])->name('add'); //Add Form
        Route::get('/edit/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'edit'])->name('edit'); //Add Form
        Route::post('/update/{id}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'update'])->name('update'); //Add Form
        Route::get('/delete/{id}', ['middleware' => ['can:' . config('custom_middleware.delete_customer')], 'uses' => $controller . 'delete'])->name('delete'); //Delete
        Route::get('/change-status/{id}/{active}', ['middleware' => ['can:' . config('custom_middleware.edit_customer')], 'uses' => $controller . 'changeStatus'])->name('change-status'); //Change Status
    });
});

app/Http/Controllers/Admin/Customer/CustomerController.php
<?php

namespace App\Http\Controllers\Admin\Customer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Lang;
use Helper;
use DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;
use App\SuperAdmin\Role;
use Illuminate\Support\Facades\Auth;
use App\Admin;

class CustomerController extends Controller
{

    private $langFile   = 'admin';
    private $module     = '.customer';

    public function index(Request $request)
    {
        /*
         * Get SortKey and SortOrder from helper
         */
        $sorting    = Helper::getOrderColumn($request);
        $sortKey    = $sorting['sortKey'];
        $sortVal    = $sorting['sortVal'];
        $searchText = $request->q;
        $pageLength = $request->pageLength;
        $customer   = new admin;
        $customer   = $customer->getAllData($searchText, $sortKey, $sortVal, $pageLength);
        return view('admin.customer.index', compact('customer', 'sortKey', 'sortVal', 'searchText', 'pageLength'));
    }

    public function create()
    {
        return view("admin.customer.add");
    }

    public function store(Request $request)
    {
        /*
         * Validations
         */
        $validationRule    = [];
        $validationMessage = [];
        $validationRule    = [
            'first_name' => "required",
            'last_name'  => 'required',
            'mobile'     => 'required',
            'email'      => 'required|email|unique:users,email',
            'password'   => 'required',
        ];
        $validationMessage = [
            'first_name.required' => __($this->langFile . '.error-req-first-name'),
            'last_name.required'  => __($this->langFile . '.error-req-last-name'),
            'mobile.required'     => __($this->langFile . '.error-req-telephone'),
            'email.required'      => __($this->langFile . '.error-req-email'),
            'email.email'         => __($this->langFile . '.error-email-email'),
            'email.unique'        => __($this->langFile . '.error-unique-email'),
            'password.required'   => __($this->langFile . '.error-req-password'),
        ];
        $validatedData     = $request->validate($validationRule, $validationMessage);
        DB::beginTransaction();
        try
        {
            $model             = new Admin();
            $model->first_name = $request->first_name;
            $model->last_name  = $request->last_name;
            $model->mobile     = $request->mobile;
            $model->email      = $request->email;
            $model->password   = Hash::make($request->password);
            $model->gender     = $request->gender;
            $model->address    = $request->address;
            /*
             * main save
             */
            if ($model->save())
            {
                /*
                 * Insert status Flag
                 */
                $flag        = true;
                $roleId      = 2;
//assign role
                $roleManager = \App\SuperAdmin\Role::find($roleId); //App Admin 
                $model->assignRole($roleManager);
                if ($flag)
                {
                    DB::commit();
                    $status       = 'success';
                    $message_text = __($this->langFile . '.add-success');
                    $message_text = Str::replaceFirst("#module#", __($this->langFile . $this->module), $message_text);
                }
                else
                {
                    DB::rollback();
                    $status       = 'error';
                    $message_text = __($this->langFile . '.add-error');
                    $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
                }
            }
            else
            {
                DB::rollback();
                $status       = 'error';
                $message_text = __($this->langFile . '.add-error');
                $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
            }
        }
        catch (Throwable $e)
        {
            DB::rollback();
            $status       = 'error';
            $message_text = __($this->langFile . '.add-error');
            $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
        }
        return redirect()->route('admin.customer.index')->with($status, $message_text);
    }

    public function edit($id)
    {
        $singleRecord = Admin::find($id);
        if ($singleRecord)
        {
            return view("admin.customer.edit", compact('id', 'singleRecord'));
        }
        else
        {
            $status       = 'error';
            $message_text = __($this->langFile . '.record_not_found');
        }
        return redirect()->route('admin.customer.index')->with($status, $message_text);
    }

    public function update(Request $request, $id)
    {
        $model = Admin::find($id);
        if ($model)
        {
            /*
             * Validations
             */
            $validationRule    = [];
            $validationMessage = [];
            $validationRule    = [
                'first_name' => "required",
                'last_name'  => 'required',
                'mobile'     => 'required',
                'address'    => 'required',
                'email'      => 'required|email|unique:Admin,email,' . $id . ',id,deleted_at,NULL',
            ];
            $validationMessage = [
                'first_name.required' => __($this->langFile . '.error-req-first-name'),
                'last_name.required'  => __($this->langFile . '.error-req-last-name'),
                'mobile.required'     => __($this->langFile . '.error-req-telephone'),
                'email.required'      => __($this->langFile . '.error-req-email'),
                'email.email'         => __($this->langFile . '.error-email-email'),
                'email.unique'        => __($this->langFile . '.error-unique-email'),
                'address.required'    => __($this->langFile . '.error-req-required'),
            ];
            $validatedData     = $request->validate($validationRule, $validationMessage);

            $model->first_name = $request->first_name;
            $model->last_name  = $request->last_name;
            $model->mobile     = $request->mobile;
            $model->email      = $request->email;
            $model->address    = $request->address;
            $model->gender     = $request->gender;
            try
            {
                DB::beginTransaction();
                $flag = true;
                if ($model->save())
                {

                    /*
                     * Insert status Flag
                     */
                    if ($flag)
                    {
                        DB::commit();
                        $status       = 'success';
                        $message_text = __($this->langFile . '.update-success');
                        $message_text = Str::replaceFirst("#module#", __($this->langFile . $this->module), $message_text);
                    }
                    else
                    {
                        DB::rollback();
                        $status       = 'error';
                        $message_text = __($this->langFile . '.update-error');
                        $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
                    }
                }
                else
                {
                    DB::rollback();
                    $status       = 'error';
                    $message_text = __($this->langFile . '.update-error');
                    $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
                }
            }
            catch (Throwable $e)
            {
                DB::rollback();
                $status       = 'error';
                $message_text = __($this->langFile . '.update-error');
                $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
            }
        }
        else
        {
            DB::rollback();
            $status       = 'error';
            $message_text = __($this->langFile . '.update-error');
            $message_text = Str::replaceFirst("#module#", strtolower(__($this->langFile . $this->module)), $message_text);
        }
        return redirect()->route('admin.customer.index')->with($status, $message_text);
    }

    /*
     * Change Status
     */

    public function changeStatus($id, $active)
    {
        $singleRecord = admin::find($id);
        if ($singleRecord && $active == 0 || $active == 1)
        {
            DB::beginTransaction();
            try
            {
                $singleRecord->is_active = $active;
                if ($singleRecord->save())
                {
                    DB::commit();
                    $status       = 'success';
                    $message_text = __($this->langFile . '.status-change-success');
                    $message_text = Str::replaceFirst("#module#", __($this->langFile . $this->module), $message_text);
                    if ($active == 1)
                    {
                        $message_text = Str::replaceFirst("#status#", '"' . (__($this->langFile . '.active') . '"'), $message_text);
                    }
                    else
                    {
                        $message_text = Str::replaceFirst("#status#", '"' . (__($this->langFile . '.in_active') . '"'), $message_text);
                    }
                }
                else
                {
                    DB::rollback();
                    $status       = 'error';
                    $message_text = __($this->langFile . '.status-change-error');

resources/views/admin/customer/edit.blade.php
@extends('layout/main')
@section('page_title',  trans('admin.customer'))
@section('additional_css')
<link rel="stylesheet" href="{{asset('plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('public/custom/css/custom.css')}}">
@endsection
@section('content')
@include('layout/toaster')
<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('admin.customer')}}</h1>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{route('admin.home.index')}}">{{__('admin.home')}}</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.customer.index')}}">{{__('admin.customer')}}</a></li>
                        <li class="breadcrumb-item active">{{__('admin.edit')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="card {{config('custom.card-primary')}}">
                <div class="card-header">
                    <h3 class="card-title">{{__('admin.edit')}}</h3>
                </div>
                <form method="post" action="{{route('admin.customer.update',['id' => $singleRecord->id])}}">
                    @csrf
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4 col-sm-12">
                                <div class="form-group"> 
                                    <label>{{__('admin.first_name')}}</label><span class="required"></span>
                                    <input type="text" name="first_name" placeholder="{{__('admin.first_name')}}" class="form-control text-input length-30 {{ $errors->has('first_name') ?'is-invalid':'' }}"  value="{{old('first_name',$singleRecord->first_name)}}">
                                    @error('first_name')
                                    <div class="text-red">{!! $message !!}</div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-12">
                                <div class="form-group"> 
                                    <label>{{__('admin.last_name')}}</label><span class="required"></span>
                                    <input type="text" name="last_name" placeholder="{{__('admin.last_name')}}" class="form-control text-input length-30 {{ $errors->has('last_name') ?'is-invalid':'' }}" value="{{old('last_name',$singleRecord->last_name)}}">
                                    @error('last_name')
                                    <div class="text-red">{!! $message !!}</div>
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-4 col-sm-12">
                                <div class="form-group"> 
                                    <label>{{__('admin.telephone')}}</label><span class="required"></span>
                                    <input type="text" name="mobile" placeholder="{{__('admin.telephone')}}" class="form-control number-input length-10 {{ $errors->has('mobile') ?'is-invalid':'' }}" value="{{old('mobile',$singleRecord->mobile)}}">
                                    @error('mobile')
                                    <div class="text-red">{!! $message !!}</div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 col-sm-12">
                                <div class="form-group"> 
                                    <label>{{__('admin.email_address')}}</label><span class="required"></span>
                                    <input type="email" name="email" placeholder="{{__('admin.email_address')}}" class="form-control text-input length-50 {{ $errors->has('email') ?'is-invalid':'' }}" value="{{old('email',$singleRecord->email)}}">
                                    @error('email')
                                    <div class="text-red">{!! $message !!}</div>
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-4 col-sm-12">
                                <div class="form-group">
                                    <label class="radio-label">{{__('admin.gender')}}</label>
                                    <div class="radiobox-row">
                                        <label class="radiobox-col">
                                            <input type="radio" checked="checked" id="male" name="gender"  value="1" {{old('gender',$singleRecord->gender) == '1' ? 'checked' : '' }} >
                                            <span class="checkmark"></span>
                                            {{__('admin.male')}}
                                        </label>
                                        <label class="radiobox-col">
                                            <input type="radio" name="gender" id="female" value="0" {{old('gender',$singleRecord->gender) == '0' ? 'checked' : '' }} >
                                            <span class="checkmark"></span>
                                            {{__('admin.female')}}
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 col-sm-12">
                            <div class="form-group"> 
                                <label>{{__('admin.address')}}</label><span class="required"></span>
                                <textarea type="text" name="address" placeholder="{{__('admin.address')}}" class="form-control text-input length-50 {{ $errors->has('address') ?'is-invalid':'' }}" >{{old('address',$singleRecord->address)}}</textarea>
                                @error('address')
                                <div class="text-red">{!! $message !!}</div>
                                @endif
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <span class="float-left">{!!__('admin.additional_notes')!!}</span>
                        <div class="btn-toolbar float-right">
                            <div class="btn-group mr-2">
                                <a href="{{route('admin.customer.index')}}" class="{{config('custom.btn-danger-form')}}" title="{{__('admin.cancel')}}">{{__('admin.cancel')}}</a>
                            </div>
                            <div class="btn-group">
                                <button type="submit" class="{{config('custom.btn-success-form')}}" title="{{__('admin.update')}}">{{__('admin.update')}}</button>
                            </div>
                        </div>
                    </div>
            </div>
            </form>
        </div>
    </section>
</div>
@endsection
@section('page_specific_js')
@include('layout/select2')
<script>

</script>
@endsection

resources/views/admin/customer/index.blade.php
@extends('layout/main')
@section('page_title',  trans('admin.customer'))
@section('additional_css')
<link rel="stylesheet" href="{{asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('public/custom/css/custom.css')}}">
@endsection
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            @include('layout/toaster')
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('admin.customer')}}</h1>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{route('admin.home.index')}}">{{__('admin.home')}}</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.customer.index')}}">{{__('admin.customer')}}</a></li>
                        <li class="breadcrumb-item active">{{__('admin.list')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-12">
                    <form class="list-table" method="get" action="{{route('admin.customer.index')}}">
                        <div class="card {{config('custom.card-primary')}}">
                            <div class="table-card card-header pl-0"> 
                                <div class="card-tools w-100">
                                    <div class="input-group input-group-sm float-right custom-search">
                                        <input type="text" name="q" class="form-control float-right float-sm-right" placeholder="{{__('admin.search')}}" value="{{isset($searchText)?$searchText:''}}">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-default" title="{{__('admin.search')}}"><i class="fas fa-search"></i></button>
                                        </div>
                                        <a class="pl-2" href="{{route('admin.customer.add')}}"><button type="button" class="{{config('custom.btn-primary','btn btn-outline-primary')}} add-new-btn" title="{{__('admin.add')}}">{{__('admin.add')}}</button></a>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <table class="table normal-table table-striped">
                                <thead>
                                    <tr>
                                        <th>{{__('admin.first_column')}}</th>
                                        <th class="asc-desc" id="@if($sortKey=='first_name'){{$sortVal}}@endif">{{__('admin.full_name')}}<input @if($sortKey!='first_name')disabled=""@endif  type="hidden" name="first_name" value="@if($sortKey=='first_name'){{$sortVal}}@endif"></th>
                                        <th class="asc-desc" id="@if($sortKey=='email'){{$sortVal}}@endif">{{__('admin.email')}}<input @if($sortKey!='email')disabled=""@endif  type="hidden" name="email" value="@if($sortKey=='email'){{$sortVal}}@endif"></th>
                                        <th class="asc-desc" id="@if($sortKey=='mobile'){{$sortVal}}@endif">{{__('admin.additional_info')}}<input @if($sortKey!='mobile')disabled=""@endif  type="hidden" name="mobile" value="@if($sortKey=='mobile'){{$sortVal}}@endif"></th>
                                        <th  class="text-center">{{__('admin.no_of_order')}}</th>
                                        <th class="asc-desc text-center" id="@if($sortKey=='is_active'){{$sortVal}}@endif">{{__('admin.status')}}<input @if($sortKey!='is_active')disabled=""@endif  type="hidden" name="is_active" value="@if($sortKey=='is_active'){{$sortVal}}@endif"></th>
                                        <th class="text-center">{{__('admin.action')}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($customer as $record)
                                    <tr>
                                        <td>{{$loop->iteration}}</td>
                                        <td>{{ucfirst($record->first_name.' '.$record->last_name)}}</td>
                                        <td>{{ucfirst($record->email)}}</td>
                                        <td><label>{{__('admin.phone')}} :</label> {{$record->mobile}}</td>
                                        <?php
                                        $orderCount = $record->getOrderCount($record->id);
                                        ?>
                                        <td class="text-center">{{$orderCount}}</td>
                                        <td class="text-center">
                                            @if($record->is_active)
                                            <span class="{{config('custom.badge-success','badge bg-success')}}">{{__('admin.active')}}</span>
                                            @else
                                            <span class="{{config('custom.badge-danger','badge bg-danger')}}">{{__('admin.in_active')}}</span> 
                                            @endif
                                        </td>
                                        <td class="text-center">
                                            <!--<a href="{{route('admin.customer.edit',['id' => $record->id])}}"><button type="button" class="{{config('custom.btn-primary','btn btn-outline-primary btn-sm')}}" title="{{__('admin.edit')}}"><i class="fas fa-edit"></i></button></a>-->
                                            @if($record->is_active)
                                            <a href="{{route('admin.customer.change-status',['id'=>$record->id,'active'=>0]).'?'.http_build_query($_GET)}}"><button type="button" class="{{config('custom.btn-danger','btn btn-outline-danger btn-sm')}}" title="{{__('admin.click_in_active')}}"><i class="fas fa-times"></i></button></a>
                                            @else
                                            <a href="{{route('admin.customer.change-status',['id'=>$record->id,'active'=>1]).'?'.http_build_query($_GET)}}"><button type="button" class="{{config('custom.btn-success','btn btn-outline-success btn-sm')}}" title="{{__('admin.click_active')}}"><i class="fas fa-check"></i></button></a>
                                            @endif
                                            <a onclick="showSweetAlert('{{route('admin.customer.delete',['id'=>$record->id])}}')"><button type="button" class="{{config('custom.btn-danger','btn btn-outline-danger btn-sm')}}" title="{{__('admin.delete')}}"><i class="fas fa-trash"></i></button></a>
                                        </td>
                                    </tr>
                                    @empty
                                    @endforelse
                                </tbody>
                            </table>
                            <!-- /.card-body -->
                        </div>
                        <div class="table-pagination pt20 float-right">
                            {{$customer->appends(request()->input())->links()}}
                        </div>
                    </form>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection
@section('page_specific_js')
@include('common/sorting')
@include('layout/sweetalert')
@include('layout/datatable')
@endsection